"""
KING Relationship Inferences
----------------------------

KING is a toolset to robustly identify different types of relatedness. Unlike
other methods, you should only remove markers that fail QC (i.e., don't mess
with MAF or LD filters).

Kinship Table
+++++++++++++

.. csv-table::
    :header: name, dtype, description

    ID1, string, Individual ID for the first individual of the pair
    ID2, string, Individual ID for the second individual of the pair
    N_SNP, UInt32, The number of SNPs that do not have missing genotypes in either of the individual
    HetHet, float, Proportion of SNPs with double heterozygotes (e.g., AG and AG)
    IBS0, float, Proportion of SNPs with zero IBS (identical-by-state) (e.g., AA and GG)
    Kinship, float, Estimated kinship coefficient from the SNP data
    relationship, string, The assigned relationship based on Kinship

Relationship Values
*******************

Categories were assigned based on Kinship ranges provided in the `KING manual`_.

.. csv-table::
    :header: name, description

    ID, duplicate or MZ twin
    D1, 1st degree relative
    D2, 2nd degree relative
    D3, 3rd degree relative
    UN, unrelated

.. _KING manual: http://people.virginia.edu/~wc9c/KING/manual.html#WITHIN

References:
    - http://people.virginia.edu/~wc9c/KING/manual.html
    - Manichaikul A, Mychaleckyj JC, Rich SS, Daly K, Sale M, Chen WM (2010)
      Robust relationship inference in genome-wide association studies.
      Bioinformatics 26(22):2867-2873
"""
import pandas as pd

from cgr_gwas_qc.typing import PathLike


def read_kinship(filename: PathLike) -> pd.DataFrame:
    """Reads the table generated by ``king --kinship``.

    Reads the king file and re-assigns ID1/ID2 by sorting IDs
    alphanumerically. Assigns relationships based on Kinship ranges provided
    in KING manual.

    Returns:
        pd.DataFrame

        - ID1
        - ID2
        - N_SNP
        - HetHet
        - IBS0
        - Kinship
        - relationship {ID, D1, D2, D3, UN}

    References:
        - http://people.virginia.edu/~wc9c/KING/manual.html#WITHIN
    """
    dtypes = {
        "ID1": "string",
        "ID2": "string",
        "N_SNP": "UInt32",
        "HetHet": "float",
        "IBS0": "float",
        "Kinship": "float",
        "relationship": "string",
    }

    def _sort_ids(x: pd.Series) -> pd.Series:
        x["ID1"], x["ID2"] = sorted([x.ID1, x.ID2])
        return x

    return (
        pd.read_csv(filename, sep="\t")
        .apply(_sort_ids, axis=1)
        .assign(relationship=lambda x: x.Kinship.apply(_infer_relationship))
        .reindex(dtypes.keys(), axis=1)
    )


def _infer_relationship(king_coefficient: float):
    if king_coefficient > 0.354:
        return "ID"  # identical or MZ twin

    if 0.177 < king_coefficient <= 0.354:
        return "D1"  # 1st degree relative

    if 0.0884 < king_coefficient <= 0.177:
        return "D2"  # 2nd degree relative

    if 0.0442 < king_coefficient <= 0.0884:
        return "D3"  # 3rd degree relative

    return "UN"  # unrelated
