#!/usr/bin/python
rule copy_for_lab:
    input:
        qc = 'all_sample_qc.csv',
        known = 'concordance/KnownReplicates.csv',
        unknown = 'concordance/UnknownReplicates.csv',
        lims = outName + '_LimsUpload_' + sampSheetDate + '.csv'
    output:
        qc = 'files_for_lab/' + outName + '_all_sample_qc_' + sampSheetDate + '.csv',
        known = 'files_for_lab/' + outName + '_KnownReplicates_' + sampSheetDate + '.csv',
        unknown = 'files_for_lab/' + outName + '_UnknownReplicates_' + sampSheetDate + '.csv',
        lims = 'files_for_lab/' + outName + '_LimsUpload_' + sampSheetDate + '.csv'
    run:
        shell('''cp {input.qc} {output.qc}
cp {input.known} {output.known}
cp {input.unknown} {output.unknown}
cp {input.lims} {output.lims}
''')
