#!/usr/bin/python

rule make_control_list:
    input:
        fam = 'split_by_pop/{pop}_subjects.fam',
        sampSheet = sample_sheet
    output:
        'HWP/{pop}_controls.txt'
    run:
        with open(input.fam) as f:
            line = f.readline()
        if line == 'Too few subjects to process pop\n':
            with open(output[0], 'w') as out:
                out.write('Too few subjects to process pop\n')
        else:
            SubjectToCaCoDict = makeSubjectToCaCoDict(input.sampSheet)
            controls = []
            with open(input.fam) as f:
                for line in f:
                    sub = line.split()[1]
                    CaCo = SubjectToCaCoDict[sub]
                    if CaCo == '0':
                        controls.append(sub)
            if len(controls) < config['control_hwp_thresh']:
                shell('cp {input.fam} {output}')
            else:
                with open(output[0], 'w') as out:
                    for c in controls:
                        out.write(c + ' ' + c + '\n')
                    


rule subset_controls:
    input:
        bed = 'split_by_pop/{pop}_subjects.bed',
        bim = 'split_by_pop/{pop}_subjects.bim',
        fam = 'split_by_pop/{pop}_subjects.fam',
        keep = 'HWP/{pop}_controls.txt'
    params:
        inProj = 'split_by_pop/{pop}_subjects',
        outProj = 'HWP/{pop}_subjects'
    output:
        'HWP/{pop}_subjects.bed',
        'HWP/{pop}_subjects.bim',
        'HWP/{pop}_subjects.fam'
    run:
        with open(input.keep) as f:
            line = f.readline()
        if line == 'Too few subjects to process pop\n':
            for x in output:
                with open(x, 'w') as out:
                    out.write('Too few subjects to process pop\n')
        else:
            shell('plink --bfile {params.inProj} --keep {input.keep} --memory 10000 --make-bed --out {params.outProj}')

rule control_HWP:
    input:
        bed = 'HWP/{pop}_subjects.bed',
        bim = 'HWP/{pop}_subjects.bim',
        fam = 'HWP/{pop}_subjects.fam'
    params:
        inProj = 'HWP/{pop}_subjects',
        outProj = 'HWP/{pop}_subjects_qc'
    output:
        'HWP/{pop}_subjects_qc.hwe'
    run:
        with open(input.fam) as f:
            line = f.readline()
        if line == 'Too few subjects to process pop\n':
            with open(output[0], 'w') as out:
                out.write('Too few subjects to process pop\n')
        else:
            shell('plink --bfile {params.inProj} --autosome --maf 0.05 --hardy --memory 10000 --out {params.outProj}')

rule plot_HWP:
    input:
        'HWP/{pop}_subjects_qc.hwe'
    output:
        png = 'HWP/{pop}_subjects_qc.HWP.png',
        R = 'HWP/{pop}_subjects_qc.HWP.R',
        Rout = 'HWP/{pop}_subjects_qc.HWP.R.out'
    run:
        with open(input[0]) as f:
            line = f.readline()
        if line == 'Too few subjects to process pop\n':
            for x in output:
                with open(x, 'w') as out:
                    out.write('Too few subjects to process pop\n')
        else:
            rTxt = '''
            require(qqman)
            data <- read.table("''' + input[0] + '''", head = T)                                                                                                   
            png("''' + output.png + '''", 6.5, 6.5, "in", res = 300)
            qq(data$P, main = "''' + wildcards.pop + ''' HWP qq plot")
            dev.off()                                                                                                                                   
            '''
            with open(output.R, 'w')  as R:
                R.write(rTxt)
            shell('R --vanilla < {output.R} > {output.Rout}')
