#!/usr/bin/python

rule gtc_to_adpc:
    input:
        gtc = getGtc,
        manifest = illumina_manifest_file
    output:
        adpc = 'contam/{sample_id}.adpc.bin',
        txt = 'contam/{sample_id}.adpc.bin.numSnps.txt'
    shell:
        'module load python/2.7.5;python /DCEG/CGF/Bioinformatics/Production/Eric/scripts/gtc2adpc.py {input.gtc} {input.manifest} {output.adpc}'


rule combine_adpc:
    input:
        expand('contam/{sample_id}.adpc.bin', sample_id = SAMPLE_IDS)
    output:
        adpc = 'all_contam/contam.adpc.bin',
        txt = 'all_contam/contam.adpc.bin.sampOrder.txt'
    params:
        adpc_dir = 'contam'
    shell:
        'module load python/2.7.5;python /DCEG/CGF/Bioinformatics/Production/Eric/scripts/combineAdpc.py {params.adpc_dir} {output.adpc}' 


rule combine_contam_txt:
    input:
        expand('contam/{sample_id}.adpc.bin.numSnps.txt', sample_id = SAMPLE_IDS)
    output:
        'all_contam/contam.adpc.bin.numSnps.txt'
    run:
        snpCounts = []
        for i in input:
            with open(i) as f:
                line = f.readline()
                numSnps = line.strip()
                snpCounts.append(numSnps)
        numSamps = len(snpCounts)
        if len(set(snpCounts)) > 1:
            sys.exit(1)
        with open(output[0], 'w') as out:
            out.write('NumSamps\tNumSnps\n')
            out.write(str(numSamps) + '\t' + snpCounts[0] + '\n')

rule contam_test:
    input:
        adpc = 'all_contam/contam.adpc.bin',
        txt = 'all_contam/contam.adpc.bin.numSnps.txt'
    params:
        software = '/DCEG/CGF/Bioinformatics/Production/BZhu/verifyIDintensity/verifyIDintensity/verifyIDintensity'
    output:
        'contam/contam.out'
    run:
        with open(input.txt) as f:
            head = f.readline()
            line = f.readline()
        (numSamps, numSnps) = line.split()
        shell('{params.software} -m ' + numSnps + ' -n ' + numSamps + ' -v -p -i {input.adpc} > {output}')


rule combine_contam:
    input:
        contam = 'contam/contam.out',
        txt = 'all_contam/contam.adpc.bin.sampOrder.txt'
    output:
        'all_contam/contam.csv'
    run:
        with open(input.contam) as f, open(input.txt) as sampFile, open(output[0], 'w') as out:
            out.write('ID,%Mix,LLK,LLK0\n')
            head = f.readline()
            head = f.readline()
            line = f.readline()
            sampLine = sampFile.readline()
            while line != '':
                line_list = line.split()
                samp = sampLine.strip()
                line_list[0] = samp
                out.write(','.join(line_list) + '\n')
                line = f.readline()
                sampLine = sampFile.readline()

