#!/usr/bin/python

rule identifiler:
    input:
        outName + '_LimsUpload_' + sampSheetDate + '.csv',
        sampSheet = sample_sheet
    output:
        'files_for_lab/' + outName + '_Identifiler_' + sampSheetDate + '.csv'
    params:
        header = 'Sample_ID,LIMSSample_ID,Project,Project-Sample ID,SR_Subject_ID,LIMS_Individual_ID'
    run:
        headers = params.header.split(',')
        sampSheetDict = makeSampSheetDict(input.sampSheet, headers)
        with open(input[0]) as f, open(output[0], 'w') as out:
            out.write(params.header + ',Identifiler Reason\n')
            head = f.readline()
            line = f.readline()
            while line != '':
                line_list = line.rstrip().split(',')
                samp = line_list[2]
                (contam, sex, repDisc, unexpectRep) = line_list[6:]
                identReasons = []
                if contam == 'TRUE':
                    identReasons.append('Contaminated')
                if sex == 'TRUE':
                    identReasons.append('Sex Discordant')
                if unexpectRep == 'TRUE':
                    identReasons.append('Unexpected Replicate')
                if len(identReasons) > 0:
                    reason = ';'.join(identReasons)
                    out.write(','.join(sampSheetDict[samp] + [reason]) + '\n')
                line = f.readline()

