#!/usr/bin/python

rule add_CaCo_imiss:
    input:
        imiss = '{d}/samples{filt}.imiss',
        sampSheet = sample_sheet
    output:
        '{d}/samples{filt}.imiss.csv'
    run:
        sampToCaCoDict = makeSampleToCaCoDict(input.sampSheet)
        with open(input.imiss) as f, open(output[0], 'w') as out:
            head = f.readline()
            out.write('Sample_ID,CaCo,N_MISS,N_GENO,F_MISS\n')
            line = f.readline()
            while line != '':
                line_list = line.split()
                samp = line_list[1]
                CaCo = sampToCaCoDict[samp]
                if CaCo == 'NA':
                    CaCo = '2'
                out.write(','.join([samp, CaCo] + line_list[3:]) + '\n')
                line = f.readline()


rule plot_completion:
    input:
        samp = '{d}/samples{filt}.imiss.csv',
        snp = '{d}/samples{filt}.lmiss'
    output:
        pdf = '{d}/samples{filt}.completion.pdf',
        R = '{d}/samples{filt}.completion.R',
        Rout = '{d}/samples{filt}.completion.R.out'
    run:
        rTxt = '''
        colors <- c(rgb(0, 0, 1, .3), rgb(1, 0, 0, .3), rgb(0, 1, 0, .3))
        data <- read.csv("''' + input.samp + '''")
        data$CR <- 1.0 - data$F_MISS
        sortData <- data[with(data, order(data$CR)), ]
        caseCR <- data$CR[data$CaCo == 1]
        contCR <- data$CR[data$CaCo == 0]
        otherCR <- data$CR[data$CaCo == 2]
        sampQuant <- quantile(data$CR, c(.99, .95, .90, .50), na.rm = T)
        dataSnp <- read.table("''' + input.snp + '''", head = T)
        snpCR <- 1.0 - dataSnp$F_MISS[!is.na(dataSnp$F_MISS)]
        snpQuant <- quantile(snpCR, c(.99, .95, .90, .50), na.rm = T)
        a <- 0:(nrow(sortData) - 1)
        x <- 100.0 * a/length(a)
        a2 <- 0:(length(snpCR) - 1)
        x2 <- 100.0 * a2/length(a2)
        pdf("''' + output.pdf + '''")
        layout(cbind(1,2))
        par(mar= c(7,4,2,0), family = "mono")
        plot(x, sortData$CR * 100.0, xlab="Samples(%)", xlim = c(0, 100), ylim = c(90, 100), ylab="Completion Rate(%)", axes=F, pch=20, col= colors[sortData$CaCo + 1])
        axis(side=1,at= c(0,20,40,60,80,100),labels= c(0,20,40,60,80,100))
        axis(side=2,at= c(90,91,92,93,94,95,96,97,98,99,100), labels= c(90,91,92,93,94,95,96,97,98,99,100))
        abline(h=99,lty="dashed", col="gray")
        abline(h=98,lty="dashed", col="gray")
        abline(h=97,lty="dashed", col="gray")
        abline(h=96,lty="dashed", col="gray")
        abline(h=95,lty="dashed", col="gray")
        title(main= "Sample Completion",sub= "", cex=0.6)

        text <- paste("Quantiles #case #control #QC/Unknown\n",
        "      100   ", length(caseCR), "      ", length(contCR), "      ", length(otherCR), "\n",
        "      99    ", length(caseCR[caseCR <= sampQuant[1]]), "      ", length(contCR[contCR <= sampQuant[1]]), "      ", length(otherCR[otherCR <= sampQuant[1]]), "\n",
        "      95    ", length(caseCR[caseCR <= sampQuant[2]]), "      ", length(contCR[contCR <= sampQuant[2]]), "      ", length(otherCR[otherCR <= sampQuant[2]]), "\n",
        "      90    ", length(caseCR[caseCR <= sampQuant[3]]), "      ", length(contCR[contCR <= sampQuant[3]]), "      ", length(otherCR[otherCR <= sampQuant[3]]), "\n",
        "      50    ", length(caseCR[caseCR <= sampQuant[4]]), "       ", length(contCR[contCR <= sampQuant[4]]), "       ", length(otherCR[otherCR <= sampQuant[4]]), "\n",
        sep = "")
        
        legend("center", text, cex=0.6, bty="n")
        legend("bottom", legend = c("Cases", "Controls", "QC/Unknown"), col = c("red", "blue", "green"), pch = 19, cex=0.7, bty="n")

        par(mar= c(7,1,2,3))
        plot(x2, 100 * sort(snpCR), xlim= c(0, 100), ylim= c(90, 100), xlab= "Loci(%)", ylab="", type="l", axes=F)
        axis(side=1, at= c(0,20,40,60,80,100), labels= c(0,20,40,60,80,100))
        
        abline(h=99,lty="dashed", col="gray")
        abline(h=98,lty="dashed", col="gray")
        abline(h=97,lty="dashed", col="gray")
        abline(h=96,lty="dashed", col="gray")
        abline(h=95,lty="dashed", col="gray")

        naSnps <- length(dataSnp$F_MISS[is.na(dataSnp$F_MISS)])
        text <- paste("Quantiles   #Loci\n",
        "      100   ", nrow(dataSnp), "\n",
        "      99    ", length(snpCR[snpCR <= snpQuant[1]]) + naSnps, "\n",
        "      95    ", length(snpCR[snpCR <= snpQuant[2]]) + naSnps, "\n",
        "      90    ", length(snpCR[snpCR <= snpQuant[3]]) + naSnps, "\n",
        "      50    ", length(snpCR[snpCR <= snpQuant[4]]) + naSnps, "\n",
        sep = "")

        legend("center", text, cex=0.6, bty= "n")
        dev.off()
        '''
        with open(output.R, 'w')  as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')

