#!/usr/bin/python

rule idat_intensity:
    input:
        red = getRedIdat,
        green = getGreenIdat
    output:
        'idat_intensity/{idatBase}.intensity.txt'
    run:
        shell('module load R')
        
        R("""
        medianIntensIdat <- function(redIdat, greenIdat){
        require(illuminaio)
        red <- readIDAT(redIdat)
        green <- readIDAT(greenIdat)
        Intens <- red$Quants[,1] + green$Quants[,1]
        median(Intens)
        }

        medIntens <- medianIntensIdat("{input.red}", "{input.green}")
        write.table(medIntens, file = "{output}", quote = F, row.names = F, col.names = F) 
        """)

rule combine_idat_intensity:
    input:
        expand('idat_intensity/{idatBase}.intensity.txt', idatBase = idats)
    output:
        'all_sample_idat_intensity/idat_intensity.csv'
    run:
        with open(output[0], 'w') as out:
            out.write('SampId,ChipId,MedianIntensity\n')
            for i in input:
                chipId = os.path.basename(i).split('.')[0]
                sampId = chipIdToSampDict[chipId]
                with open(i) as f:
                    line = f.readline()
                medIntens = line.strip()
                out.write(','.join([sampId, chipId, medIntens]) + '\n')

