#!/usr/bin/python


rule subset_qc_subject:
    input:
        fam = 'subject_level/samples.fam',
        qc = 'all_sample_qc.csv',
        sampSheet = sample_sheet
    output:
        'sex_plot/subject_qc.csv'
    run:
        sampToCaCoDict = makeSampleToCaCoDict(input.sampSheet)
        sampDict = {}
        with open(input.fam) as f:
            for line in f:
                samp = line.split()[1]
                sampDict[samp] = 1
        with open(input.qc) as f, open(output[0], 'w') as out:
            head = f.readline()
            out.write(head.rstrip() + ',CaCo\n')
            line = f.readline()
            while line != '':
                samp = line.split(',')[7]
                CaCo = sampToCaCoDict[samp]
                if CaCo == 'NA':
                    CaCo = '2'
                if sampDict.get(samp):
                    out.write(line.rstrip() + ',' + CaCo + '\n')
                line = f.readline()



rule plot_sex:
    input:
        'sex_plot/subject_qc.csv'
    output:
        png = 'sex_plot/sex.png',
        R = 'sex_plot/sex.R',
        Rout = 'sex_plot/sex.R.out'
    run:
        rTxt = '''
colors <- c(rgb(0, 0, 1, .3), rgb(1, 0, 0, .3), rgb(.75, .75, .75, .3), rgb(0, 1, 0, .3))
data <- read.csv("''' + input[0] + '''", colClasses = rep("character", 35))
femData <- subset(data, Expected_Sex == "F")
maleData <- subset(data, Expected_Sex == "M")
yStart <- min(min(as.numeric(data$ChrX_Inbreed_estimate), na.rm = T), 0.0)
yEnd <- max(max(as.numeric(data$ChrX_Inbreed_estimate), na.rm = T), 1.0)


png("''' + output.png + '''", 6.5, 6.5, "in", res = 300)
if (nrow(femData) > 0 & nrow(maleData) > 0) {
    fem_X <- runif(nrow(femData), .8, 1.2)
    male_X <- runif(nrow(maleData), 1.8, 2.2)
    boxplot(as.numeric(femData$ChrX_Inbreed_estimate), as.numeric(maleData$ChrX_Inbreed_estimate), names = c("F", "M"),
    ylab = "ChrX Inbreed Coeff", main = "ChrX Inbreeding Coeff by Reported Sex", xlab = "Reported Sex", outline=FALSE, ylim = c(yStart, yEnd))
    points(fem_X, as.numeric(femData$ChrX_Inbreed_estimate), col = colors[as.numeric(femData$CaCo) + 1], pch = 20, cex = 0.7)
    points(male_X, as.numeric(maleData$ChrX_Inbreed_estimate), col = colors[as.numeric(maleData$CaCo) + 1], pch = 20, cex = 0.7)
} else if (nrow(femData) > 0) {
    fem_X <- runif(nrow(femData), .8, 1.2)
    boxplot(as.numeric(femData$ChrX_Inbreed_estimate), names = c("F"),
    ylab = "ChrX Inbreed Coeff", main = "ChrX Inbreeding Coeff by Reported Sex", xlab = "Reported Sex", outline=FALSE, ylim = c(yStart, yEnd),show.names=TRUE)
    points(fem_X, as.numeric(femData$ChrX_Inbreed_estimate), col = colors[as.numeric(femData$CaCo) + 1], pch = 20, cex = 0.7)

} else if (nrow(maleData) > 0) {
    male_X <- runif(nrow(maleData), .8, 1.2)
    boxplot(as.numeric(maleData$ChrX_Inbreed_estimate), names = c("M"),
    ylab = "ChrX Inbreed Coeff", main = "ChrX Inbreeding Coeff by Reported Sex", xlab = "Reported Sex", outline=FALSE, ylim = c(yStart, yEnd),show.names=TRUE)
    points(male_X, as.numeric(maleData$ChrX_Inbreed_estimate), col = colors[as.numeric(maleData$CaCo) + 1], pch = 20, cex = 0.7)

} else {
    unk_X <- runif(nrow(data), .8, 1.2)
    boxplot(as.numeric(data$ChrX_Inbreed_estimate), names = c("Unknown"),
    ylab = "ChrX Inbreed Coeff", main = "ChrX Inbreeding Coeff by Reported Sex", xlab = "Reported Sex", outline=FALSE, ylim = c(yStart, yEnd),show.names=TRUE)
    points(unk_X, as.numeric(data$ChrX_Inbreed_estimate), col = colors[as.numeric(data$CaCo) + 1], pch = 20, cex = 0.7)

}

abline(h = 0.5)                                                                                                                                                             
legend("topleft", legend = c("Cases", "Controls", "Unknown"), col = c("red", "blue", "green"), pch = 19)
dev.off()
'''
        with open(output.R, 'w')  as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')

