from cgr_gwas_qc import load_config

cfg = load_config()


################################################################################
# All Targets
################################################################################
subworkflow delivery:
    snakefile:
        cfg.subworkflow("delivery")
    workdir:
        cfg.root.as_posix()


rule run_all_subworkflows:
    input:
        delivery("subworkflow_complete/delivery"),
