from snakemake.rules import expand

from cgr_gwas_qc import load_config

cfg = load_config()

include: cfg.rules("gtc_to_plink.smk")


rule all:
    input:
        expand("plink_start/samples.{ext}", ext=["bed", "bim", "fam"])
