jobscript: jobscript.sh
cluster: submit.py
cluster-status: status.py
jobs: 1000
keep-going: true
latency-wait: 60
max-jobs-per-second: 10
max-status-checks-per-second: 10
rerun-incomplete: true
restart-times: 3
use-conda: true
