#!/usr/bin/python

rule plink_sample_qc_stats:
    input:
        '{d}/samples.bed',
        '{d}/samples.bim',
        '{d}/samples.fam'
    params:
        inProj = '{d}/samples',
        outProj = '{d}/samples{filt}'
    output:
        '{d}/samples{filt}.imiss',
        '{d}/samples{filt}.lmiss',
        '{d}/samples{filt}.sexcheck',
        '{d}/samples{filt}.frq',
        '{d}/samples{filt}.hwe'
    shell:
        'plink --bfile {params.inProj} --freq --missing --hardy --het --check-sex --memory 10000 --out {params.outProj}'


rule filter_call_rate_1:
    input:
        'plink_start/samples.bed',
        'plink_start/samples.bim',
        'plink_start/samples.fam'
    params:
        inProj = 'plink_start/samples',
        outProj = 'plink_filter_call_rate_1/samples',
        mind = str(1 - float(samp_cr_1)),
        geno = str(1 - float(snp_cr_1))
    output:
        'plink_filter_call_rate_1/samples.bed',
        'plink_filter_call_rate_1/samples.bim',
        'plink_filter_call_rate_1/samples.fam'
    shell:
        'plink --bfile {params.inProj} --mind {params.mind} --geno {params.geno} --make-bed --memory 10000 --out {params.outProj}'

rule filter_call_rate_2:
    input:
        'plink_filter_call_rate_1/samples.bed',
        'plink_filter_call_rate_1/samples.bim',
        'plink_filter_call_rate_1/samples.fam'
    params:
        inProj = 'plink_filter_call_rate_1/samples',
        outProj = 'plink_filter_call_rate_2/samples',
        mind = str(1 - float(samp_cr_2)),
        geno = str(1 - float(snp_cr_2))
    output:
        'plink_filter_call_rate_2/samples.bed',
        'plink_filter_call_rate_2/samples.bim',
        'plink_filter_call_rate_2/samples.fam'
    shell:
        'plink --bfile {params.inProj} --mind {params.mind} --geno {params.geno} --memory 10000 --make-bed --out {params.outProj}'
